version: "3"

services:
  postgres:
    image: postgres
    env_file: .env
    volumes:
        - ./postgres:/var/lib/postgresql/data
    restart: always
  K:
    image: ghcr.io/mehdy/k:v0.1.0
    env_file: .env
    restart: always
    depends_on:
      - postgres
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - K
